//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplicacion()
        {
            this.DataArea = new HashSet<DataArea>();
            this.Funcionalidad = new HashSet<Funcionalidad>();
            this.MenuMaster = new HashSet<MenuMaster>();
            this.Rol = new HashSet<Rol>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public string codAplicacion { get; set; }
        public Nullable<int> idResourceBanner { get; set; }
        public Nullable<int> idResourceLogo { get; set; }
        public Nullable<int> idResourceImgHome { get; set; }
        public Nullable<int> idResourceImgReplicaDer { get; set; }
        public Nullable<int> idResourceImgReplicaIzq { get; set; }
        public Nullable<int> idCodigoAmbiente { get; set; }
        public string nbAplicacion { get; set; }
        public bool ActivateLog { get; set; }
        public string dsTitulo { get; set; }
        public string dsSubTitulo { get; set; }
        public string noVersion { get; set; }
        public string nbInstanciaDB { get; set; }
        public string nbDB { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime feCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataArea> DataArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionalidad> Funcionalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuMaster> MenuMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
