//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataArea()
        {
            this.EmpresaXVirtual = new HashSet<EmpresaXVirtual>();
            this.EmpresaXVirtual1 = new HashSet<EmpresaXVirtual>();
        }
    
        public string cvCia { get; set; }
        public string codAplicacion { get; set; }
        public string nbEmpresa { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime feCreacion { get; set; }
        public bool esVirtual { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaXVirtual> EmpresaXVirtual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaXVirtual> EmpresaXVirtual1 { get; set; }
    }
}
