//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.DataArea = new HashSet<DataArea>();
            this.UsuarioXRol = new HashSet<UsuarioXRol>();
            this.Aplicacion = new HashSet<Aplicacion>();
        }
    
        public string nbAlias { get; set; }
        public int idCodigoTipoCuenta { get; set; }
        public string nbLanguageCulture { get; set; }
        public string noEmpleado { get; set; }
        public string nbEmpleado { get; set; }
        public string dsMail { get; set; }
        public bool esActivo { get; set; }
        public Nullable<System.DateTime> feRegistro { get; set; }
        public Nullable<bool> esSuperUsuario { get; set; }
        public string dsEmpresa { get; set; }
        public Nullable<bool> esNCPermitido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataArea> DataArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioXRol> UsuarioXRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplicacion> Aplicacion { get; set; }
    }
}
